[package]
name = "regtest"
version = "0.4.0"
authors = ["Lucas Salibian <lucas.salibian@gmail.com>"]
homepage = "https://github.com/tqoitc/regtest"
repository = "https://github.com/tqoitc/regtest"
documentation = "https://github.com/tqoitc/regtest"
readme = "README.md"
keywords = ["regex", "command"]
license = "GPL-3.0"
description = "regtest is an easy to use interactive frontend for the regex crate."
edition = "2021"

[dependencies]
regex = "1"
rustyline = "18"
bitflags = "2"
clap = "4"
directories = "6"

[profile.release]
lto = true
opt-level = 3
